### ISSUE TITLE
Update Error Processing 

### ISSUE THREAD

**Issue by JachymPutta** [Zilliqa/scilla-compiler#89]
Compiler does not build with the Master branch of Scilla. 

Built with the latest Scilla release (Scilla-v0.11.0)

Full error message:
![image](https://user-images.githubusercontent.com/67414100/152150353-f7f9a54e-bc9e-494a-aee7-2a0036593ab0.png)

**Comment by vaivaswatha** [comment]
While I try to keep `scilla-compiler` updated to work with the latest Scilla `master`, that isn't always possible as new features (and hence possible AST changes) are added to Scilla. Both developments happen in parallel.

`scilla-compiler` is known to work with https://github.com/Zilliqa/scilla/commit/47de22b4d95b6bf19a49d80aedc9f6b714938c23.

Closing this Issue. You can ping me/us directly if you plan to build scilla-compiler actively and I can help with some arrangement so that you don't get stuck on builds.

**Comment by anton-trunov** [comment]
Hey @vaivaswatha, Jachym is one of the collaborators of the scilla-chick project, he is trying to setup the compiler so that we could use randomized testing on the compiler. Let me kindly reopen this issue because scilla-chick is not compatible with that Scilla version and it appers we cannot build both projects at the moment.

**Comment by vaivaswatha** [comment]
@JachymPutta The build must now work. Please verify and close the Issue if it works for you.
