### ISSUE TITLE
Support newer LLVM versions

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/scilla-compiler#97]
We currently support LLVM 13 (and maybe some previous versions) but there are already more LLVM releases out there.

**Comment by jubnzv** [comment]
It seems, that there are no functional changes in the generated LLVM IR when building test contracts with the recent versions of LLVM.

But the problem is that the latest LLVM version available in the opam repository is 13.0.0: https://github.com/ocaml/opam-repository/tree/master/packages/llvm.

So, if one wants to use the latest LLVM, they should:
1. Install deprecated versions of `llvm` and `conf-llvm` from the `opam` to make sure that `dune` sees these libraries.
2. Build the recent version of OCaml LLVM bindings and install them in the current opam switch as it suggested [in this script](https://github.com/Zilliqa/scilla-compiler/blob/master/scripts/build_install_llvm.sh).
3. Then build the compiler.

I think we don't want to complicate the installation process for the miners by this way.
Probably, the most straightforward way to update LLVM is to create and publish the latest release ([14.0.6](https://github.com/llvm/llvm-project/releases/) is currently the stable one) to the opam repository and then just update the `llvm` dependency in our repo.

**Comment by anton-trunov** [comment]
> Probably, the most straightforward way to update LLVM is to create and publish the latest release ([14.0.6](https://github.com/llvm/llvm-project/releases/) is currently the stable one) to the opam repository and then just update the llvm dependency in our repo.

Let's go for it. It will pay off

**Comment by jubnzv** [comment]
https://github.com/ocaml/opam-repository/pull/21932
